// <auto-generated />
using System;
using DockerDemo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DockerDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260404111729_Init_Database")]
    partial class Init_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DockerDemo.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Devices, gadgets and accessories",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Printed and digital books across genres",
                            IsActive = true,
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Men's and women's apparel",
                            IsActive = true,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Home goods, decor and kitchenware",
                            IsActive = true,
                            Name = "Home"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Toys, games and children's products",
                            IsActive = true,
                            Name = "Toys"
                        });
                });

            modelBuilder.Entity("DockerDemo.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("longtext");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 75, DateTimeKind.Unspecified).AddTicks(9043), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USD",
                            Description = "Over-ear, noise-cancelling headphones with long battery life.",
                            IsActive = true,
                            Name = "Wireless Headphones",
                            Price = 129.99m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 75, DateTimeKind.Unspecified).AddTicks(9047), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(760), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USD",
                            Description = "Fast-charge USB-C wall adapter, 30W.",
                            IsActive = true,
                            Name = "Smartphone Charger",
                            Price = 19.99m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(760), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USD",
                            Description = "Comprehensive guide to modern C# and .NET development.",
                            IsActive = true,
                            Name = "Modern C# Programming",
                            Price = 39.95m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(773), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USD",
                            Description = "Illustrated storybook for ages 3-7.",
                            IsActive = true,
                            Name = "Children's Picture Book",
                            Price = 12.50m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(774), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(776), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USD",
                            Description = "100% cotton, regular fit.",
                            IsActive = true,
                            Name = "Men's Casual T-Shirt",
                            Price = 24.00m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(776), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(790), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USD",
                            Description = "Stretch denim, slim fit.",
                            IsActive = true,
                            Name = "Women's Jeans",
                            Price = 49.99m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(790), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(792), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USD",
                            Description = "16-piece porcelain dinnerware set.",
                            IsActive = true,
                            Name = "Ceramic Dinner Set",
                            Price = 79.99m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(793), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(796), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USD",
                            Description = "1.7L stainless steel kettle with auto shut-off.",
                            IsActive = true,
                            Name = "Electric Kettle",
                            Price = 29.95m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(796), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(798), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USD",
                            Description = "200-piece construction set for ages 6+.",
                            IsActive = true,
                            Name = "Building Blocks Set",
                            Price = 34.99m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(799), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(801), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USD",
                            Description = "Battery-powered RC car with rechargeable battery.",
                            IsActive = true,
                            Name = "Remote Control Car",
                            Price = 44.50m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 11, 17, 26, 76, DateTimeKind.Unspecified).AddTicks(801), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DockerDemo.Models.Product", b =>
                {
                    b.HasOne("DockerDemo.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
