apiVersion: v1
kind: Service
metadata:
  name: my-backend-service  ## IMPORTANT: Frontend will use this
  labels:
    app: demo-application
    tier: backend   
spec:
  selector:
    app: demo-application
  ports:
    - name: http
      port: 8080 
      targetPort: 8080