name: CI-CD Pipeline (Kind)

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: backend-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    # ---------------------------
    # Install kubectl
    # ---------------------------
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4

    # ---------------------------
    # Install Kind
    # ---------------------------
    - name: Install Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    # ---------------------------
    # Create Kubernetes Cluster
    # ---------------------------
    - name: Create Kind cluster
      run: kind create cluster

    # ---------------------------
    # Build Docker Image
    # ---------------------------
    - name: Build Image
      run: |
        docker build -t $IMAGE_NAME ./Backend

    # ---------------------------
    # Load Image into Kind
    # ---------------------------
    - name: Load image into cluster
      run: |
        kind load docker-image $IMAGE_NAME

    # ---------------------------
    # Deploy to Kubernetes
    # ---------------------------
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/

    # ---------------------------
    # Verify Deployment
    # ---------------------------
    - name: Verify Pods
      run: |
        kubectl get pods