name: CI-CD Pipeline (Local Minikube)

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: backend-api

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    # ---------------------------
    # Ensure Minikube is running
    # ---------------------------
    - name: Start Minikube (if not running)
      run: |
        minikube status

    # ---------------------------
    # Use Minikube Docker daemon
    # ---------------------------
    - name: Use Minikube Docker
      run: |
        eval $(minikube docker-env)

    # ---------------------------
    # Build Image INSIDE Minikube
    # ---------------------------
    - name: Build Image
      run: |
        docker build -t backend-api ./Backend

    # ---------------------------
    # Deploy to Kubernetes
    # ---------------------------
    - name: Deploy
      run: |
        kubectl apply -f k8s/

    - name: Restart Deployment
      run: |
        kubectl rollout restart deployment backend-api

    # ---------------------------
    # Verify
    # ---------------------------
    - name: Verify Pods
      run: |
        kubectl get pods
